// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gcamlhmjrljjygiizavg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdjYW1saG1qcmxqanlnaWl6YXZnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYyNDE3NjYsImV4cCI6MjA3MTgxNzc2Nn0.sDclYzYNg4ai8ZatiO0NFEjI69yjQ1VzNXfD-2wWCnM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
    detectSessionInUrl: true
  }
});